# Distributed under the Boost Software License, Version 1.0.
# Repeatable native package matrix; library children always use their install presets.
cmake_minimum_required(VERSION 3.24)
foreach(required STLAB_SOURCE EXECUTION_SOURCE TOOLKIT_SOURCE VERIFY_PARENT VERIFY_ROOT)
  if(NOT DEFINED ${required} OR "${${required}}" STREQUAL "")
    message(FATAL_ERROR "Required path: ${required}")
  endif()
endforeach()
foreach(source STLAB_SOURCE EXECUTION_SOURCE TOOLKIT_SOURCE)
  file(REAL_PATH "${${source}}" ${source})
endforeach()
cmake_path(ABSOLUTE_PATH VERIFY_PARENT NORMALIZE OUTPUT_VARIABLE parent)
cmake_path(ABSOLUTE_PATH VERIFY_ROOT NORMALIZE OUTPUT_VARIABLE root)
if(EXISTS "${parent}")
  file(REAL_PATH "${parent}" parent)
endif()
if(EXISTS "${root}")
  file(REAL_PATH "${root}" root)
endif()
cmake_path(IS_PREFIX parent "${root}" NORMALIZE in_scope)
if(NOT in_scope OR NOT root STREQUAL "${parent}/execution-packages" OR
   NOT EXISTS "${STLAB_SOURCE}/CMakePresets.json" OR
   NOT EXISTS "${EXECUTION_SOURCE}/test/verify_package.cmake" OR
   NOT EXISTS "${TOOLKIT_SOURCE}/cpp-library.cmake")
  message(FATAL_ERROR "Refusing unscoped verification root: ${root}")
endif()
foreach(source STLAB_SOURCE EXECUTION_SOURCE TOOLKIT_SOURCE)
  cmake_path(IS_PREFIX root "${${source}}" NORMALIZE contains_source)
  if(contains_source)
    message(FATAL_ERROR "Verification root contains a source tree: ${root}")
  endif()
endforeach()
file(REMOVE_RECURSE "${root}")
file(MAKE_DIRECTORY "${root}")
find_program(ctest NAMES ctest REQUIRED)

function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result
    OUTPUT_VARIABLE output ERROR_VARIABLE error)
  file(APPEND "${root}/commands.log" "Command: ${ARGV}\nExit: ${result}\n${output}\n${error}\n")
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Command (${result}): ${ARGV}\n${output}\n${error}")
  endif()
  if(NOT error STREQUAL "")
    message("${error}")
  endif()
endfunction()

set(settings "-DCPM_cpp-library_SOURCE:PATH=${TOOLKIT_SOURCE}"
  "-DCPM_stlab-execution_SOURCE:PATH=${EXECUTION_SOURCE}" -DBUILD_TESTING=OFF)
set(execution_settings)
foreach(setting STLAB_EXECUTION_SHARED STLAB_TASK_SYSTEM TEST_COMPILER TEST_MAKE_PROGRAM)
  if(DEFINED ${setting} AND NOT "${${setting}}" STREQUAL "")
    list(APPEND execution_settings "-D${setting}=${${setting}}")
    if(setting STREQUAL "TEST_COMPILER")
      list(APPEND settings "-DCMAKE_CXX_COMPILER:FILEPATH=${TEST_COMPILER}")
    elseif(setting STREQUAL "TEST_MAKE_PROGRAM")
      list(APPEND settings "-DCMAKE_MAKE_PROGRAM:FILEPATH=${TEST_MAKE_PROGRAM}")
    else()
      list(APPEND settings "-D${setting}=${${setting}}")
    endif()
  endif()
endforeach()
set(independent "${root}/independent/execution-packages")
run("${CMAKE_COMMAND}" "-DEXECUTION_SOURCE:PATH=${EXECUTION_SOURCE}"
  "-DTOOLKIT_SOURCE:PATH=${TOOLKIT_SOURCE}" "-DVERIFY_PARENT:PATH=${root}/independent"
  "-DVERIFY_ROOT:PATH=${independent}" ${execution_settings}
  -P "${EXECUTION_SOURCE}/test/verify_package.cmake")
set(execution_prefix "${independent}/prefix")

# Validates package-local metadata, version ownership, ordering, and relocatability.
function(check_package prefix package expected_version)
  file(GLOB_RECURSE configs "${prefix}/${package}Config.cmake" "${prefix}/*/${package}Config.cmake")
  list(LENGTH configs count)
  if(NOT count EQUAL 1)
    message(FATAL_ERROR "Expected exactly one ${package} config in ${prefix}: ${configs}")
  endif()
  list(GET configs 0 config_path)
  file(READ "${config_path}" config)
  get_filename_component(config_dir "${config_path}" DIRECTORY)
  file(READ "${config_dir}/${package}ConfigVersion.cmake" version)
  if(NOT version MATCHES "set\\(PACKAGE_VERSION \"${expected_version}\"\\)")
    message(FATAL_ERROR "Incorrect ${package} version: expected ${expected_version}\n${version}")
  endif()
  if(package STREQUAL "stlab")
    string(FIND "${config}" "find_dependency(stlab-execution" dependency)
    string(FIND "${config}" "stlabTargets.cmake" targets)
    if(dependency LESS 0 OR targets LESS dependency)
      message(FATAL_ERROR "STLab must find execution before loading its targets.")
    endif()
  elseif(config MATCHES "find_dependency\\(stlab[ )]")
    message(FATAL_ERROR "Execution must not depend on STLab.")
  endif()
  foreach(source STLAB_SOURCE EXECUTION_SOURCE TOOLKIT_SOURCE)
    file(GLOB metadata "${config_dir}/*.cmake")
    foreach(path IN LISTS metadata)
      file(READ "${path}" content)
      string(FIND "${content}" "${${source}}" embedded)
      if(NOT embedded EQUAL -1)
        message(FATAL_ERROR "Source path embedded in ${path}")
      endif()
    endforeach()
  endforeach()
  file(APPEND "${root}/metadata.txt" "${config_path}\n${config}\n${version}\n")
endfunction()

# Builds/runs installed or source STLab consumers without execution source include paths.
function(consume name prefix execution_prefix)
  run("${CMAKE_COMMAND}" -S "${STLAB_SOURCE}/test/package" -B "${root}/${name}" -G Ninja
    "-DCMAKE_PREFIX_PATH=${prefix}" "-DEXECUTION_PREFIX:PATH=${execution_prefix}"
    -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release ${ARGN})
  run("${CMAKE_COMMAND}" --build "${root}/${name}" --parallel 8)
  run("${ctest}" --test-dir "${root}/${name}" --output-on-failure)
endfunction()

foreach(case combined stlab-only execution-only)
  set(binary "${root}/${case}/library")
  set(prefix "${root}/${case}/prefix")
  if(case STREQUAL "stlab-only")
    set(execution_install OFF)
  else()
    set(execution_install ON)
  endif()
  if(case STREQUAL "execution-only")
    set(stlab_install OFF)
  else()
    set(stlab_install ON)
  endif()
  run("${CMAKE_COMMAND}" --preset=install -S "${STLAB_SOURCE}" -B "${binary}" ${settings}
    "-DSTLAB_INSTALL=${stlab_install}" "-DSTLAB_EXECUTION_INSTALL=${execution_install}")
  run("${CMAKE_COMMAND}" --build "${binary}" --parallel 8)
  run("${CMAKE_COMMAND}" --install "${binary}" --prefix "${prefix}")
  file(READ "${binary}/include/stlab/config.hpp" stlab_config)
  foreach(component MAJOR MINOR PATCH)
    string(REGEX MATCH "STLAB_VERSION_${component}\\(\\) ([0-9]+)" matched "${stlab_config}")
    if(matched STREQUAL "")
      message(FATAL_ERROR "Missing actual STLab ${component} project version.")
    endif()
    set(version_${component} "${CMAKE_MATCH_1}")
  endforeach()
  set(stlab_version "${version_MAJOR}.${version_MINOR}.${version_PATCH}")
  if(stlab_install)
    check_package("${prefix}" stlab "${stlab_version}")
    if(NOT EXISTS "${prefix}/include/stlab/config.hpp" OR
       NOT EXISTS "${prefix}/include/stlab/concurrency/future.hpp")
      message(FATAL_ERROR "STLab selected but its canonical headers are missing.")
    endif()
  else()
    file(GLOB_RECURSE forbidden "${prefix}/*stlabConfig*.cmake" "${prefix}/*stlabTargets*.cmake")
    if(forbidden OR EXISTS "${prefix}/include/stlab/config.hpp" OR
       EXISTS "${prefix}/include/stlab/concurrency/future.hpp")
      message(FATAL_ERROR "STLab OFF installed STLab artifacts: ${forbidden}")
    endif()
  endif()
  if(execution_install)
    # Nested execution has no release tag; no global version override is permitted.
    file(READ "${binary}/_deps/stlab-execution-build/include/stlab/execution/config.hpp" execution_config)
    foreach(component MAJOR MINOR PATCH)
      string(REGEX MATCH "STLAB_EXECUTION_VERSION_${component}\\(\\) ([0-9]+)" matched "${execution_config}")
      if(matched STREQUAL "")
        message(FATAL_ERROR "Missing actual execution ${component} project version.")
      endif()
      set(version_${component} "${CMAKE_MATCH_1}")
    endforeach()
    check_package("${prefix}" stlab-execution "${version_MAJOR}.${version_MINOR}.${version_PATCH}")
    if(NOT EXISTS "${prefix}/include/stlab/execution/config.hpp")
      message(FATAL_ERROR "Execution selected but its configuration header is missing.")
    endif()
  else()
    file(GLOB_RECURSE forbidden "${prefix}/*stlab-executionConfig*.cmake")
    if(forbidden OR EXISTS "${prefix}/include/stlab/execution/config.hpp" OR
       EXISTS "${prefix}/include/stlab/concurrency/task.hpp")
      message(FATAL_ERROR "Execution OFF installed execution artifacts: ${forbidden}")
    endif()
  endif()
  if(case STREQUAL "combined")
    consume(combined-consumer "${prefix}" "${prefix}")
    # Install independently versioned execution into that same prefix as well.
    run("${CMAKE_COMMAND}" --install "${independent}/library" --prefix "${prefix}")
    check_package("${prefix}" stlab "${stlab_version}")
    check_package("${prefix}" stlab-execution 1.0.0)
    consume(independent-combined-consumer "${prefix}" "${prefix}")
  elseif(case STREQUAL "stlab-only")
    consume(stlab-only-consumer "${prefix}" "${execution_prefix}")
  else()
    run("${CMAKE_COMMAND}" -S "${EXECUTION_SOURCE}/test/package" -B "${root}/execution-only-consumer"
      -G Ninja "-DCMAKE_PREFIX_PATH:PATH=${prefix}" -DCMAKE_CXX_STANDARD=20
      "-DEXECUTION_PREFIX:PATH=${prefix}" -DCMAKE_BUILD_TYPE=Release)
    run("${CMAKE_COMMAND}" --build "${root}/execution-only-consumer" --parallel 8)
    run("${ctest}" --test-dir "${root}/execution-only-consumer" --output-on-failure)
  endif()
endforeach()

# Compare actual exported file sets, not shared directory names.
file(READ "${root}/combined-consumer/package-evidence.txt" stlab_evidence)
file(READ "${independent}/consumer-20/package-evidence.txt" execution_evidence)
string(REGEX MATCH "headers=([^\n]+)" matched "${stlab_evidence}")
set(stlab_headers "${CMAKE_MATCH_1}")
string(REGEX MATCH "headers=([^\n]+)" matched "${execution_evidence}")
set(execution_headers "${CMAKE_MATCH_1}")
foreach(owner stlab execution)
  set(canonical_headers)
  foreach(header IN LISTS ${owner}_headers)
    string(REGEX REPLACE "^.*[/\\\\]include[/\\\\]" "" canonical "${header}")
    list(APPEND canonical_headers "${canonical}")
  endforeach()
  set(${owner}_canonical "${canonical_headers}")
endforeach()
foreach(header IN LISTS stlab_canonical)
  if(header IN_LIST execution_canonical)
    message(FATAL_ERROR "Duplicate installed header ownership: ${header}")
  endif()
endforeach()
file(WRITE "${root}/header-ownership.txt"
  "STLab: ${stlab_canonical}\nExecution: ${execution_canonical}\nIntersection: empty\n")

# This invocation intentionally has no execution source override.
consume(source-consumer "${root}/combined/prefix" "${root}/combined/prefix"
  "-DSTLAB_PACKAGE_SOURCE:PATH=${STLAB_SOURCE}"
  "-DCPM_cpp-library_SOURCE:PATH=${TOOLKIT_SOURCE}" -DCPM_USE_LOCAL_PACKAGES=ON)

if(WIN32 AND STLAB_EXECUTION_SHARED)
  find_program(dumpbin NAMES dumpbin REQUIRED)
  foreach(binary
      "${independent}/consumer-17/consumer.exe"
      "${independent}/consumer-20/consumer.exe"
      "${root}/combined-consumer/consumer.exe" "${root}/combined-consumer/legacy.exe"
      "${root}/independent-combined-consumer/consumer.exe" "${root}/independent-combined-consumer/legacy.exe"
      "${root}/stlab-only-consumer/consumer.exe" "${root}/stlab-only-consumer/legacy.exe"
      "${root}/execution-only-consumer/consumer.exe"
      "${root}/source-consumer/consumer.exe" "${root}/source-consumer/legacy.exe")
    execute_process(COMMAND "${dumpbin}" /imports "${binary}" RESULT_VARIABLE result
      OUTPUT_VARIABLE imports ERROR_VARIABLE error)
    file(APPEND "${root}/dll-imports.txt" "${binary}\n${imports}\n${error}\n")
    if(NOT result EQUAL 0 OR NOT imports MATCHES "execution\\.dll")
      message(FATAL_ERROR "Expected C ABI-only execution DLL imports: ${binary}\n${imports}")
    endif()
    string(REPLACE "\n" ";" lines "${imports}")
    set(in_execution FALSE)
    foreach(line IN LISTS lines)
      string(STRIP "${line}" line)
      if(line MATCHES "^[A-Za-z0-9_.-]+\\.dll$")
        if(line STREQUAL "execution.dll")
          set(in_execution TRUE)
        else()
          set(in_execution FALSE)
        endif()
      elseif(in_execution AND line MATCHES "^[0-9A-Fa-f][0-9A-Fa-f]?[0-9A-Fa-f]?[0-9A-Fa-f]?[ \t]+([^ \t\r\n]+)$")
        set(symbol "${CMAKE_MATCH_1}")
        # The existing link-time data guard is mandated by the extraction spec.
        # It is not a C++ runtime entry point; all runtime calls must use the C ABI.
        if(symbol MATCHES "^\\?value@\\?\\$task_storage_abi_guard@.*@execution_detail@execution_v[0-9_]+@stlab@@2EB$")
          file(APPEND "${root}/dll-imports.txt" "Preserved ABI data guard: ${symbol}\n")
        elseif(NOT symbol MATCHES "^(stlab_v2_[a-z_]+|stlab_pre_exit|stlab_at_pre_exit)$")
          message(FATAL_ERROR "Non-C-ABI runtime import from execution: ${symbol}")
        endif()
      endif()
    endforeach()
  endforeach()
endif()
message(STATUS "PASS execution/STLab package matrix: ${root}")
